# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
